name=input('Digite seu nome:')
idade=input('Digite sua idade:')
print('Olá,' + name +'. Você tem ' + idade + ' anos.')
matricula=input('Digite sua matricula:')
print('Sua matrícula é a número ' + matricula + '.')
ddd=input('Digite o DDD:')
telefone=input('Digite seu telefone:')
print('Seu número de telefone é ' + ddd + telefone +'.')
nascimento=input('Digite sua data de nascimento:')
print('Você nasceu em ' + nascimento + '.')
